// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sln.Estoque.Infra.Data.Context;

#nullable disable

namespace Sln.Estoque.Infra.Data.Migrations
{
    [DbContext(typeof(SQLServerContext))]
    [Migration("20230328185430_Updating Layout Entity")]
    partial class UpdatingLayoutEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sln.Estoque.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Material"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ribbon"
                        });
                });

            modelBuilder.Entity("Sln.Estoque.Domain.Entities.Layout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<int>("Multiplier")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityPosition")
                        .HasColumnType("int");

                    b.Property<string>("ViewName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Layouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "_Aramis",
                            Method = 1,
                            Multiplier = 1,
                            QuantityPosition = 0,
                            ViewName = "Aramis"
                        },
                        new
                        {
                            Id = 2,
                            FileName = "CK-JEANS-COMPOSICAO-",
                            Method = 2,
                            Multiplier = 1,
                            QuantityPosition = 1,
                            ViewName = "CK Jeans Composição"
                        },
                        new
                        {
                            Id = 3,
                            FileName = "PREÇO__",
                            Method = 2,
                            Multiplier = 1,
                            QuantityPosition = 1,
                            ViewName = "Dudalina (preço)"
                        },
                        new
                        {
                            Id = 4,
                            FileName = "TAG ",
                            Method = 1,
                            Multiplier = 2,
                            QuantityPosition = 0,
                            ViewName = "Tag Renner"
                        },
                        new
                        {
                            Id = 5,
                            FileName = "Dafiti_",
                            Method = 1,
                            Multiplier = 1,
                            QuantityPosition = 0,
                            ViewName = "Dafiti"
                        });
                });

            modelBuilder.Entity("Sln.Estoque.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CodeProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CodeProduct = "P1098",
                            Name = "Tag 30x56x3",
                            Price = 48.65m,
                            Quantity = 54,
                            UnitId = 1,
                            UpdateTime = new DateTime(2023, 3, 28, 15, 54, 30, 599, DateTimeKind.Local).AddTicks(7704)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CodeProduct = "P6540",
                            Name = "Nylon 35mm",
                            Price = 23.50m,
                            Quantity = 20,
                            UnitId = 2,
                            UpdateTime = new DateTime(2023, 3, 28, 15, 54, 30, 599, DateTimeKind.Local).AddTicks(7713)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CodeProduct = "P3517",
                            Name = "Nylon 45mm",
                            Price = 29.48m,
                            Quantity = 12,
                            UnitId = 2,
                            UpdateTime = new DateTime(2023, 3, 28, 15, 54, 30, 599, DateTimeKind.Local).AddTicks(7714)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CodeProduct = "P8590",
                            Name = "Ribbon Cera",
                            Price = 37.42m,
                            Quantity = 8,
                            UnitId = 2,
                            UpdateTime = new DateTime(2023, 3, 28, 15, 54, 30, 599, DateTimeKind.Local).AddTicks(7715)
                        });
                });

            modelBuilder.Entity("Sln.Estoque.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = "Alta",
                            LevelId = 1
                        },
                        new
                        {
                            Id = 2,
                            Level = "Media",
                            LevelId = 2
                        },
                        new
                        {
                            Id = 3,
                            Level = "Baixa",
                            LevelId = 3
                        });
                });

            modelBuilder.Entity("Sln.Estoque.Domain.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Milhar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Unidade"
                        },
                        new
                        {
                            Id = 3,
                            Name = "M²"
                        });
                });

            modelBuilder.Entity("Sln.Estoque.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gérson Bonetti",
                            Password = "lotr",
                            RoleId = 1,
                            Username = "@gb"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gabriel Mundt",
                            Password = "rainbowsix",
                            RoleId = 1,
                            Username = "@md"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yuri Laurindo",
                            Password = "impressora",
                            RoleId = 2,
                            Username = "@yl"
                        },
                        new
                        {
                            Id = 4,
                            Name = "João Lopes",
                            Password = "mequi",
                            RoleId = 3,
                            Username = "@jv"
                        });
                });

            modelBuilder.Entity("Sln.Estoque.Domain.Entities.Product", b =>
                {
                    b.HasOne("Sln.Estoque.Domain.Entities.Category", "Category")
                        .WithMany("ProductList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sln.Estoque.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Sln.Estoque.Domain.Entities.User", b =>
                {
                    b.HasOne("Sln.Estoque.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sln.Estoque.Domain.Entities.Category", b =>
                {
                    b.Navigation("ProductList");
                });
#pragma warning restore 612, 618
        }
    }
}
